#
#spring.datasource.url=jdbc:mysql://localhost:3306/logistic?createTableIfNotExists=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
#spring.jpa.hibernate.ddl-auto = update
#
##server.port=8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: LOGISTIC_SERVICE
